version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.14
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@react-navigation/core"
    versions:
    - 5.15.1
    - 5.15.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: semantic-release
    versions:
    - 17.2.3
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: babel-jest
    versions:
    - 26.6.3
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-is
    versions:
    - 17.0.1
