language: node_js
node_js:
  - node # current node version (may be duplicate, but that's OK)
jobs:
  include:
    - stage: install
      script: yarn
    - stage: deploy
      script: npx semantic-release
